/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as MultasRouteImport } from './routes/multas'
import { Route as MediosPagoRouteImport } from './routes/medios-pago'
import { Route as EnforcementRouteImport } from './routes/enforcement'
import { Route as ControladoresRouteImport } from './routes/controladores'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OverviewBackupRouteImport } from './routes/overview.backup'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as VehiclesBackup20260611035904RouteImport } from './routes/vehicles.backup.20260611035904'
import { Route as IndexBackup20260611030009RouteImport } from './routes/index.backup.20260611030009'
import { Route as VehiclesBackupFinal20260611041949RouteImport } from './routes/vehicles.backup.final.20260611041949'
import { Route as MultasBackupFinal20260613034429RouteImport } from './routes/multas.backup.final.20260613034429'
import { Route as MultasBackupApi20260613032848RouteImport } from './routes/multas.backup.api.20260613032848'
import { Route as IndexBackupFinal20260611041949RouteImport } from './routes/index.backup.final.20260611041949'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const MultasRoute = MultasRouteImport.update({
  id: '/multas',
  path: '/multas',
  getParentRoute: () => rootRouteImport,
} as any)
const MediosPagoRoute = MediosPagoRouteImport.update({
  id: '/medios-pago',
  path: '/medios-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcementRoute = EnforcementRouteImport.update({
  id: '/enforcement',
  path: '/enforcement',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoresRoute = ControladoresRouteImport.update({
  id: '/controladores',
  path: '/controladores',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewBackupRoute = OverviewBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => OverviewRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesBackup20260611035904Route =
  VehiclesBackup20260611035904RouteImport.update({
    id: '/backup/20260611035904',
    path: '/backup/20260611035904',
    getParentRoute: () => VehiclesRoute,
  } as any)
const IndexBackup20260611030009Route =
  IndexBackup20260611030009RouteImport.update({
    id: '/index/backup/20260611030009',
    path: '/index/backup/20260611030009',
    getParentRoute: () => rootRouteImport,
  } as any)
const VehiclesBackupFinal20260611041949Route =
  VehiclesBackupFinal20260611041949RouteImport.update({
    id: '/backup/final/20260611041949',
    path: '/backup/final/20260611041949',
    getParentRoute: () => VehiclesRoute,
  } as any)
const MultasBackupFinal20260613034429Route =
  MultasBackupFinal20260613034429RouteImport.update({
    id: '/backup/final/20260613034429',
    path: '/backup/final/20260613034429',
    getParentRoute: () => MultasRoute,
  } as any)
const MultasBackupApi20260613032848Route =
  MultasBackupApi20260613032848RouteImport.update({
    id: '/backup/api/20260613032848',
    path: '/backup/api/20260613032848',
    getParentRoute: () => MultasRoute,
  } as any)
const IndexBackupFinal20260611041949Route =
  IndexBackupFinal20260611041949RouteImport.update({
    id: '/index/backup/final/20260611041949',
    path: '/index/backup/final/20260611041949',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/controladores': typeof ControladoresRoute
  '/enforcement': typeof EnforcementRoute
  '/medios-pago': typeof MediosPagoRoute
  '/multas': typeof MultasRouteWithChildren
  '/overview': typeof OverviewRouteWithChildren
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/overview/backup': typeof OverviewBackupRoute
  '/admin/': typeof AdminIndexRoute
  '/index/backup/20260611030009': typeof IndexBackup20260611030009Route
  '/vehicles/backup/20260611035904': typeof VehiclesBackup20260611035904Route
  '/index/backup/final/20260611041949': typeof IndexBackupFinal20260611041949Route
  '/multas/backup/api/20260613032848': typeof MultasBackupApi20260613032848Route
  '/multas/backup/final/20260613034429': typeof MultasBackupFinal20260613034429Route
  '/vehicles/backup/final/20260611041949': typeof VehiclesBackupFinal20260611041949Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/controladores': typeof ControladoresRoute
  '/enforcement': typeof EnforcementRoute
  '/medios-pago': typeof MediosPagoRoute
  '/multas': typeof MultasRouteWithChildren
  '/overview': typeof OverviewRouteWithChildren
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/overview/backup': typeof OverviewBackupRoute
  '/admin': typeof AdminIndexRoute
  '/index/backup/20260611030009': typeof IndexBackup20260611030009Route
  '/vehicles/backup/20260611035904': typeof VehiclesBackup20260611035904Route
  '/index/backup/final/20260611041949': typeof IndexBackupFinal20260611041949Route
  '/multas/backup/api/20260613032848': typeof MultasBackupApi20260613032848Route
  '/multas/backup/final/20260613034429': typeof MultasBackupFinal20260613034429Route
  '/vehicles/backup/final/20260611041949': typeof VehiclesBackupFinal20260611041949Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/controladores': typeof ControladoresRoute
  '/enforcement': typeof EnforcementRoute
  '/medios-pago': typeof MediosPagoRoute
  '/multas': typeof MultasRouteWithChildren
  '/overview': typeof OverviewRouteWithChildren
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/overview/backup': typeof OverviewBackupRoute
  '/admin/': typeof AdminIndexRoute
  '/index/backup/20260611030009': typeof IndexBackup20260611030009Route
  '/vehicles/backup/20260611035904': typeof VehiclesBackup20260611035904Route
  '/index/backup/final/20260611041949': typeof IndexBackupFinal20260611041949Route
  '/multas/backup/api/20260613032848': typeof MultasBackupApi20260613032848Route
  '/multas/backup/final/20260613034429': typeof MultasBackupFinal20260613034429Route
  '/vehicles/backup/final/20260611041949': typeof VehiclesBackupFinal20260611041949Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/controladores'
    | '/enforcement'
    | '/medios-pago'
    | '/multas'
    | '/overview'
    | '/settings'
    | '/vehicles'
    | '/admin/login'
    | '/admin/users'
    | '/overview/backup'
    | '/admin/'
    | '/index/backup/20260611030009'
    | '/vehicles/backup/20260611035904'
    | '/index/backup/final/20260611041949'
    | '/multas/backup/api/20260613032848'
    | '/multas/backup/final/20260613034429'
    | '/vehicles/backup/final/20260611041949'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/controladores'
    | '/enforcement'
    | '/medios-pago'
    | '/multas'
    | '/overview'
    | '/settings'
    | '/vehicles'
    | '/admin/login'
    | '/admin/users'
    | '/overview/backup'
    | '/admin'
    | '/index/backup/20260611030009'
    | '/vehicles/backup/20260611035904'
    | '/index/backup/final/20260611041949'
    | '/multas/backup/api/20260613032848'
    | '/multas/backup/final/20260613034429'
    | '/vehicles/backup/final/20260611041949'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/controladores'
    | '/enforcement'
    | '/medios-pago'
    | '/multas'
    | '/overview'
    | '/settings'
    | '/vehicles'
    | '/admin/login'
    | '/admin/users'
    | '/overview/backup'
    | '/admin/'
    | '/index/backup/20260611030009'
    | '/vehicles/backup/20260611035904'
    | '/index/backup/final/20260611041949'
    | '/multas/backup/api/20260613032848'
    | '/multas/backup/final/20260613034429'
    | '/vehicles/backup/final/20260611041949'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ControladoresRoute: typeof ControladoresRoute
  EnforcementRoute: typeof EnforcementRoute
  MediosPagoRoute: typeof MediosPagoRoute
  MultasRoute: typeof MultasRouteWithChildren
  OverviewRoute: typeof OverviewRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  VehiclesRoute: typeof VehiclesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  IndexBackup20260611030009Route: typeof IndexBackup20260611030009Route
  IndexBackupFinal20260611041949Route: typeof IndexBackupFinal20260611041949Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multas': {
      id: '/multas'
      path: '/multas'
      fullPath: '/multas'
      preLoaderRoute: typeof MultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medios-pago': {
      id: '/medios-pago'
      path: '/medios-pago'
      fullPath: '/medios-pago'
      preLoaderRoute: typeof MediosPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcement': {
      id: '/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof EnforcementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladores': {
      id: '/controladores'
      path: '/controladores'
      fullPath: '/controladores'
      preLoaderRoute: typeof ControladoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/backup': {
      id: '/overview/backup'
      path: '/backup'
      fullPath: '/overview/backup'
      preLoaderRoute: typeof OverviewBackupRouteImport
      parentRoute: typeof OverviewRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/backup/20260611035904': {
      id: '/vehicles/backup/20260611035904'
      path: '/backup/20260611035904'
      fullPath: '/vehicles/backup/20260611035904'
      preLoaderRoute: typeof VehiclesBackup20260611035904RouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/index/backup/20260611030009': {
      id: '/index/backup/20260611030009'
      path: '/index/backup/20260611030009'
      fullPath: '/index/backup/20260611030009'
      preLoaderRoute: typeof IndexBackup20260611030009RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/backup/final/20260611041949': {
      id: '/vehicles/backup/final/20260611041949'
      path: '/backup/final/20260611041949'
      fullPath: '/vehicles/backup/final/20260611041949'
      preLoaderRoute: typeof VehiclesBackupFinal20260611041949RouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/multas/backup/final/20260613034429': {
      id: '/multas/backup/final/20260613034429'
      path: '/backup/final/20260613034429'
      fullPath: '/multas/backup/final/20260613034429'
      preLoaderRoute: typeof MultasBackupFinal20260613034429RouteImport
      parentRoute: typeof MultasRoute
    }
    '/multas/backup/api/20260613032848': {
      id: '/multas/backup/api/20260613032848'
      path: '/backup/api/20260613032848'
      fullPath: '/multas/backup/api/20260613032848'
      preLoaderRoute: typeof MultasBackupApi20260613032848RouteImport
      parentRoute: typeof MultasRoute
    }
    '/index/backup/final/20260611041949': {
      id: '/index/backup/final/20260611041949'
      path: '/index/backup/final/20260611041949'
      fullPath: '/index/backup/final/20260611041949'
      preLoaderRoute: typeof IndexBackupFinal20260611041949RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MultasRouteChildren {
  MultasBackupApi20260613032848Route: typeof MultasBackupApi20260613032848Route
  MultasBackupFinal20260613034429Route: typeof MultasBackupFinal20260613034429Route
}

const MultasRouteChildren: MultasRouteChildren = {
  MultasBackupApi20260613032848Route: MultasBackupApi20260613032848Route,
  MultasBackupFinal20260613034429Route: MultasBackupFinal20260613034429Route,
}

const MultasRouteWithChildren =
  MultasRoute._addFileChildren(MultasRouteChildren)

interface OverviewRouteChildren {
  OverviewBackupRoute: typeof OverviewBackupRoute
}

const OverviewRouteChildren: OverviewRouteChildren = {
  OverviewBackupRoute: OverviewBackupRoute,
}

const OverviewRouteWithChildren = OverviewRoute._addFileChildren(
  OverviewRouteChildren,
)

interface VehiclesRouteChildren {
  VehiclesBackup20260611035904Route: typeof VehiclesBackup20260611035904Route
  VehiclesBackupFinal20260611041949Route: typeof VehiclesBackupFinal20260611041949Route
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesBackup20260611035904Route: VehiclesBackup20260611035904Route,
  VehiclesBackupFinal20260611041949Route:
    VehiclesBackupFinal20260611041949Route,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ControladoresRoute: ControladoresRoute,
  EnforcementRoute: EnforcementRoute,
  MediosPagoRoute: MediosPagoRoute,
  MultasRoute: MultasRouteWithChildren,
  OverviewRoute: OverviewRouteWithChildren,
  SettingsRoute: SettingsRoute,
  VehiclesRoute: VehiclesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  IndexBackup20260611030009Route: IndexBackup20260611030009Route,
  IndexBackupFinal20260611041949Route: IndexBackupFinal20260611041949Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
